name: Check Nix flake
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch: # allow manual trigger
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run nix flake check
        run: nix flake check
